In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pickle

In [6]:
df=pd.read_csv("CarPricesPrediction.csv",index_col=0)

In [7]:
df.sample(10)

          Make   Model  Year  Mileage  Condition     Price
729  Chevrolet   F-150  2021    34932  Excellent  19253.50
752      Honda   Civic  2011    77760       Good  27111.90
635  Chevrolet   Camry  2010   136821       Good  25159.05
834       Ford   Camry  2019   137827       Good  16108.65
852       Ford  Altima  2014    44172  Excellent  25791.50
903      Honda   Camry  2010    61450  Excellent  28927.60
739  Chevrolet   F-150  2016    11712       Good  25414.40
286     Nissan   Civic  2021   106793  Excellent  15660.45
771  Chevrolet   F-150  2019    13554       Good  22322.40
650      Honda  Altima  2021   142456       Good  13877.30

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Make       1000 non-null   str
 1   Model      1000 non-null   str
 2   Year       1000 non-null   int64
 3   Mileage    1000 non-null   int64
 4   Condition  1000 non-null   str
 5   Price      1000 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 65.6 KB

In [18]:
df["Model"]=df["Model"].str.replace("-","")

In [19]:
df

          Make      Model  Year  Mileage  Condition     Price
0         Ford  Silverado  2022    18107  Excellent  19094.75
1       Toyota  Silverado  2014    13578  Excellent  27321.10
2    Chevrolet      Civic  2016    46054       Good  23697.30
3         Ford      Civic  2022    34981  Excellent  18251.05
4    Chevrolet      Civic  2019    63565  Excellent  19821.85
..         ...        ...   ...      ...        ...       ...
995     Nissan      Camry  2010   149032  Excellent  24548.50
996  Chevrolet       F150  2014    20608  Excellent  26969.70
997       Ford     Altima  2016   109851       Good  20507.55
998     Toyota  Silverado  2010    11704       Good  31414.90
999     Nissan  Silverado  2017   128390  Excellent  18580.60

[1000 rows x 6 columns]

In [20]:
x=df.drop("Price",axis=1)
y=df["Price"]

In [21]:
x

          Make      Model  Year  Mileage  Condition
0         Ford  Silverado  2022    18107  Excellent
1       Toyota  Silverado  2014    13578  Excellent
2    Chevrolet      Civic  2016    46054       Good
3         Ford      Civic  2022    34981  Excellent
4    Chevrolet      Civic  2019    63565  Excellent
..         ...        ...   ...      ...        ...
995     Nissan      Camry  2010   149032  Excellent
996  Chevrolet       F150  2014    20608  Excellent
997       Ford     Altima  2016   109851       Good
998     Toyota  Silverado  2010    11704       Good
999     Nissan  Silverado  2017   128390  Excellent

[1000 rows x 5 columns]

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [52]:
cat_cols=x_train.select_dtypes(exclude=["number"]).columns
cat_cols

Index(['Make', 'Model', 'Condition'], dtype='str')

In [35]:
numeric_cols = x_train.select_dtypes(include=["number"]).columns.tolist()
cat_cols = x_train.select_dtypes(exclude=["number"]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), cat_cols),
        
    ],
    remainder="passthrough"
)

In [36]:
sc=StandardScaler()

In [43]:
pipeline = Pipeline([("preprocess", preprocessor),("sc",StandardScaler()), ("model", LinearRegression())])

In [44]:
pipeline.fit(x_train, y_train)
preds = pipeline.predict(x_test)
print("MSE:", mean_squared_error(y_test, preds))
print("R2:", r2_score(y_test, preds))

MSE: 0.0040604297519897725
R2: 0.9999999997630694

In [45]:
pickle.dump(pipeline,open("car_price_prediction_model.pkl","wb"))

In [49]:
pipeline.predict(x_test.iloc[2:3])

array([22958.28735792])

In [50]:
x_test.iloc[2:3]

          Make   Model  Year  Mileage Condition
452  Chevrolet  Altima  2013   120835      Good