In [1]:
import pandas as pd

In [46]:
df=pd.read_csv("placements.csv")
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [51]:
x=df.iloc[:,0].values.reshape(-1,1)
y=df.iloc[:,-1].values
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [52]:
lr=LinearRegression()

In [53]:
lr.fit(X_train, Y_train)

LinearRegression()

In [54]:
lr.coef_

array([0.57425647])

In [55]:
lr.intercept_

-1.02700693745421

In [56]:
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [73]:
lr.predict(df.iloc[0]["cgpa"].reshape(1,1))

array([2.92962016])

In [59]:
df.iloc[1]["cgpa"]

5.12

In [62]:
0.57425647*7.21+(-1.02700693745421)

3.11338221124579

In [94]:
class practicalLR:

    def __init__(self):
        self.m=None
        self.b=None

    def fit(self,X_train,Y_train):
        num=0
        den=0

        for i in range(X_train.shape[0]):
            
            num= num+ (X_train[i]-X_train.mean())*(Y_train[i]-Y_train.mean())
            den=den+(X_train[i]-X_train.mean())*(X_train[i]-X_train.mean())  

        self.m=num/den
        self.b=Y_train.mean()-(self.m*X_train.mean()) 
        print(self.m,self.b)   

    def predict(self,X_test):

        return self.m*X_test+self.b

In [95]:
LR=practicalLR()

In [96]:
LR.fit(X_train,Y_train)

[0.57425647] [-1.02700694]

In [98]:
LR.predict(6.89)

array([2.92962016])

In [99]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [100]:
y_pred=lr.predict(X_test)

In [101]:
mean_absolute_error(Y_test,y_pred)

0.23150985393278373

In [102]:
mean_squared_error(Y_test,y_pred)

0.08417638361329657

In [103]:
r2_score(Y_test,y_pred)

0.7730984312051673

In [104]:
import numpy as np
np.sqrt(mean_squared_error(Y_test,y_pred))

0.2901316659954521

In [106]:
1-(((1-r2_score(Y_test,y_pred))*(40-1))/(40-1-1))

0.7671273372895138

In [105]:
X_test.shape

(40, 1)